# tag_Name_ansible_app_collector.yml
# --------------------
# 
# Variables for EC2 instances named "ansible_app_collector"
---
ansible_ssh_private_key_file: /Users/sunxia/Downloads/aws-cn-perm/app_lvs.pem