---
- name: Launch EC2 instances
  ec2:
    image:             "{{ item.image }}"
    instance_type:     "{{ item.instance_type }}"
    group:             "{{ item.group }}"
    instance_tags:     "{{ item.instance_tags }}"
    count_tag:         "{{ item.count_tag }}"
    exact_count:       "{{ item.exact_count }}"
    vpc_subnet_id:     "{{ item.vpc_subnet_id }}"
    assign_public_ip:  "{{ item.assign_public_ip }}"
    key_name:          "{{ item.key_name }}"
    ebs_optimized:     "{{ item.ebs_optimized }}"
    termination_protection: "{{ item.termination_protection }}"
    volumes:           "{{ item.volumes}}"
  with_items:
    "{{ ec2_instances }}"
  register: ec2

#- name: associate new elastic IPs with each of the instances
#  ec2_eip:
#    device_id: "{{ item }}"
#    region: "{{ region }}"
#  with_items: "{{ ec2.instance_ids }}"

- debug: var=ec2

- name: Create Empty List for Instances
  set_fact:
    instances: []

- name: Put Instance Into The List
  set_fact:
    instances: "{{ instances }} + {{ item.instances }}" 
  with_items:
    - "{{ ec2.results }}"

- debug: var=instances

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ instances }}"
  when: item.public_dns_name | trim != ""
  register: ec2_ssh

- debug: var=ec2_ssh